'use strict';
// AVR-Libc catalogue — data only (no vscode dependencies).
// Descriptions summarise the avr-libc user manual (https://www.nongnu.org/avr-libc/user-manual/)
// and were cross-checked against the avr-libc 2.2.0 release documentation
// (avr-libc-user-manual-2.2.0.pdf — the version shipped with current avr-gcc).
const MODULES = [
    {
        id: 'io',
        header: 'avr/io.h',
        summary: 'All device-specific I/O register definitions; the -mmcu= compiler flag decides which avr/ioXXXX.h header is pulled in.',
        include: '#include <avr/io.h>',
        functions: [
            { name: '(registers)', signature: 'PORTB, DDRB, PINB, TCNT1, ADMUX, UCSR0A…', desc: 'SFR register and bit names for the selected device — the exact set depends on the MCU.' },
        ],
        macros: [
            { name: '_BV(bit)', desc: 'Creates a bitmask (1 << bit) for register manipulation (defined in avr/sfr_defs.h).' },
            { name: 'bit_is_set(sfr, bit)', desc: 'Tests whether the given register bit is 1.' },
            { name: 'bit_is_clear(sfr, bit)', desc: 'Tests whether the given register bit is 0.' },
            { name: 'loop_until_bit_is_set(sfr, bit)', desc: 'Busy-waits until the given register bit becomes 1.' },
            { name: 'loop_until_bit_is_clear(sfr, bit)', desc: 'Busy-waits until the given register bit becomes 0.' },
        ],
        notes: 'Include FIRST in every program; the register set is selected automatically by the -mmcu=<device> compiler flag, so the same source builds for any AVR. Individual bit names reuse the register name (PORTB0, ADSC, TXEN0…).',
    },
    {
        id: 'interrupt',
        header: 'avr/interrupt.h',
        summary: 'Global interrupt control and the ISR() macro for defining interrupt service routines.',
        include: '#include <avr/interrupt.h>',
        functions: [
            { name: 'sei', signature: 'void sei(void)', desc: 'Enables interrupts globally by executing the SEI instruction (macro that sets the I bit in SREG).' },
            { name: 'cli', signature: 'void cli(void)', desc: 'Disables interrupts globally by executing the CLI instruction (macro that clears the I bit in SREG).' },
        ],
        macros: [
            { name: 'ISR(vector, attributes…)', desc: 'Defines an interrupt service routine for a vector; optional attributes are ISR_BLOCK (default), ISR_NOBLOCK, ISR_NAKED.' },
            { name: 'BADISR_vect', desc: 'Catch-all vector name (alias of __vector_default) for an ISR that handles unexpected, unimplemented interrupts.' },
            { name: 'EMPTY_INTERRUPT(vector)', desc: 'Defines an ISR containing just a reti, without any register saving.' },
            { name: 'ISR_ALIAS(vector, target)', desc: 'Makes one vector jump to the ISR already defined for another vector.' },
        ],
        notes: 'Vector names come from the device header and follow the pattern <PERIPH>_<EVENT>_vect, e.g. INT0_vect, TIMER0_OVF_vect, USART_RX_vect, ADC_vect. Write ISRs as ISR(TIMER0_OVF_vect) { … }; they are entered through the vector table with interrupts disabled.',
    },
    {
        id: 'sleep',
        header: 'avr/sleep.h',
        summary: 'Sleep-mode control: pick a mode, then issue the SLEEP instruction.',
        include: '#include <avr/sleep.h>',
        functions: [
            { name: 'set_sleep_mode', signature: 'void set_sleep_mode(uint8_t mode)', desc: 'Selects which of the SLEEP_MODE_* constants the next SLEEP instruction will use.' },
            { name: 'sleep_enable', signature: 'void sleep_enable(void)', desc: 'Sets the Sleep Enable (SE) bit in the sleep control register.' },
            { name: 'sleep_disable', signature: 'void sleep_disable(void)', desc: 'Clears the Sleep Enable (SE) bit again.' },
            { name: 'sleep_cpu', signature: 'void sleep_cpu(void)', desc: 'Executes the SLEEP instruction itself (call sleep_enable() beforehand).' },
            { name: 'sleep_mode', signature: 'void sleep_mode(void)', desc: 'One-shot convenience macro: sleep_enable(), sleep_cpu(), sleep_disable() in sequence.' },
            { name: 'sleep_bod_disable', signature: 'void sleep_bod_disable(void)', desc: 'Turns the brown-out detector off right before sleeping (not available on all devices).' },
        ],
        macros: [
            { name: 'SLEEP_MODE_IDLE', desc: 'Idle: CPU clock stopped, timers/UART/ADC keep running.' },
            { name: 'SLEEP_MODE_ADC', desc: 'ADC noise reduction: only the ADC and its clock keep running.' },
            { name: 'SLEEP_MODE_PWR_DOWN', desc: 'Power-down: all oscillators halted; wake via external interrupt or watchdog.' },
            { name: 'SLEEP_MODE_PWR_SAVE', desc: 'Power-save: like power-down but Timer2 keeps running on the async 32 kHz crystal.' },
            { name: 'SLEEP_MODE_STANDBY', desc: 'Standby: like power-down but the main oscillator keeps running for fast wake-up.' },
            { name: 'SLEEP_MODE_EXT_STANDBY', desc: 'Extended standby: like standby but Timer2 also keeps running.' },
        ],
        notes: 'Recommended sequence: set_sleep_mode(SLEEP_MODE_PWR_DOWN); sleep_enable(); sleep_cpu(); sleep_disable(); — this avoids losing wake-up events between enabling SE and sleeping. The SLEEP_MODE_* constants are supplied by the device header; not every mode exists on every MCU.',
    },
    {
        id: 'wdt',
        header: 'avr/wdt.h',
        summary: 'Watchdog timer control with symbolic timeout constants.',
        include: '#include <avr/wdt.h>',
        functions: [
            { name: 'wdt_enable', signature: 'void wdt_enable(const uint8_t timeout)', desc: 'Enables the watchdog timer with one of the WDTO_* timeout constants.' },
            { name: 'wdt_disable', signature: 'void wdt_disable(void)', desc: 'Disables the watchdog timer (performs the required WDCE/WDE timed register sequence).' },
            { name: 'wdt_reset', signature: 'void wdt_reset(void)', desc: 'Feeds the watchdog by executing the single wdr instruction.' },
        ],
        macros: [
            { name: 'WDTO_15MS', desc: 'Watchdog timeout of 15 ms.' },
            { name: 'WDTO_30MS', desc: 'Watchdog timeout of 30 ms.' },
            { name: 'WDTO_60MS', desc: 'Watchdog timeout of 60 ms.' },
            { name: 'WDTO_120MS', desc: 'Watchdog timeout of 120 ms.' },
            { name: 'WDTO_250MS', desc: 'Watchdog timeout of 250 ms.' },
            { name: 'WDTO_500MS', desc: 'Watchdog timeout of 500 ms.' },
            { name: 'WDTO_1S', desc: 'Watchdog timeout of 1 s.' },
            { name: 'WDTO_2S', desc: 'Watchdog timeout of 2 s.' },
            { name: 'WDTO_4S', desc: 'Watchdog timeout of 4 s.' },
            { name: 'WDTO_8S', desc: 'Watchdog timeout of 8 s (not available on all devices).' },
        ],
        notes: 'Enable the watchdog once in main() and call wdt_reset() from the main loop — a hung program then resets automatically after the timeout. wdt_enable()/wdt_disable() handle the device-specific timed write sequences; wdt_reset() costs exactly one instruction.',
    },
    {
        id: 'eeprom',
        header: 'avr/eeprom.h',
        summary: 'EEPROM read/write/update primitives for bytes, words, dwords, floats and blocks.',
        include: '#include <avr/eeprom.h>',
        functions: [
            { name: 'eeprom_read_byte', signature: 'uint8_t eeprom_read_byte(const uint8_t *__p)', desc: 'Reads one byte from the EEPROM address __p.' },
            { name: 'eeprom_write_byte', signature: 'void eeprom_write_byte(uint8_t *__p, uint8_t __value)', desc: 'Writes one byte to EEPROM, blocking until the write cycle finishes.' },
            { name: 'eeprom_update_byte', signature: 'void eeprom_update_byte(uint8_t *__p, uint8_t __value)', desc: 'Writes one byte only if it differs from the stored value, saving EEPROM wear.' },
            { name: 'eeprom_read_word', signature: 'uint16_t eeprom_read_word(const uint16_t *__p)', desc: 'Reads a 16-bit word from EEPROM.' },
            { name: 'eeprom_write_word', signature: 'void eeprom_write_word(uint16_t *__p, uint16_t __value)', desc: 'Writes a 16-bit word to EEPROM.' },
            { name: 'eeprom_update_word', signature: 'void eeprom_update_word(uint16_t *__p, uint16_t __value)', desc: 'Writes a 16-bit word only if it differs from the stored value.' },
            { name: 'eeprom_read_dword', signature: 'uint32_t eeprom_read_dword(const uint32_t *__p)', desc: 'Reads a 32-bit double word from EEPROM.' },
            { name: 'eeprom_write_dword', signature: 'void eeprom_write_dword(uint32_t *__p, uint32_t __value)', desc: 'Writes a 32-bit double word to EEPROM.' },
            { name: 'eeprom_update_dword', signature: 'void eeprom_update_dword(uint32_t *__p, uint32_t __value)', desc: 'Writes a 32-bit double word only if it differs from the stored value.' },
            { name: 'eeprom_read_float', signature: 'float eeprom_read_float(const float *__p)', desc: 'Reads a float from EEPROM.' },
            { name: 'eeprom_write_float', signature: 'void eeprom_write_float(float *__p, float __value)', desc: 'Writes a float to EEPROM.' },
            { name: 'eeprom_update_float', signature: 'void eeprom_update_float(float *__p, float __value)', desc: 'Writes a float only if it differs from the stored value.' },
            { name: 'eeprom_read_block', signature: 'void eeprom_read_block(void *__dst, const void *__src, size_t __n)', desc: 'Copies __n bytes from an EEPROM address (__src) into a RAM buffer.' },
            { name: 'eeprom_write_block', signature: 'void eeprom_write_block(const void *__src, void *__dst, size_t __n)', desc: 'Copies __n bytes from RAM to an EEPROM address (__dst).' },
            { name: 'eeprom_update_block', signature: 'void eeprom_update_block(const void *__src, void *__dst, size_t __n)', desc: 'Copies a block to EEPROM, skipping bytes that already hold the target value.' },
            { name: 'eeprom_busy_wait', signature: 'void eeprom_busy_wait(void)', desc: 'Spins until the EEPROM controller has finished any pending operation (macro).' },
        ],
        macros: [
            { name: 'EEMEM', desc: 'Variable attribute that places an object in the .eeprom section (uint8_t eeFoo EEMEM = 42;).' },
            { name: 'E2END', desc: 'Address of the last EEPROM byte (EEPROM size minus 1); comes from the device header.' },
            { name: 'eeprom_is_ready()', desc: 'Tests whether the EEPROM controller is idle.' },
        ],
        notes: 'Prefer the update_* functions — they compare before writing and avoid wearing out cells. EEMEM objects land in the .eeprom section of the ELF/HEX and are programmed separately (avrdude -U eeprom:w:…). The library disables interrupts around each byte write to protect the timed EEPROM sequence.',
    },
    {
        id: 'pgmspace',
        header: 'avr/pgmspace.h',
        summary: 'Storing and reading constant data in flash instead of RAM — essential on AVRs with tiny RAM.',
        include: '#include <avr/pgmspace.h>',
        functions: [
            { name: 'pgm_read_byte', signature: 'uint8_t pgm_read_byte(address_short)', desc: 'Macro that reads one byte from flash at a 16-bit (near) byte address.' },
            { name: 'pgm_read_word', signature: 'uint16_t pgm_read_word(address_short)', desc: 'Macro that reads a 16-bit word from flash at a 16-bit (near) byte address.' },
            { name: 'pgm_read_dword', signature: 'uint32_t pgm_read_dword(address_short)', desc: 'Macro that reads a 32-bit double word from flash.' },
            { name: 'pgm_read_float', signature: 'float pgm_read_float(address_short)', desc: 'Macro that reads a float from flash.' },
            { name: 'strcpy_P', signature: 'char *strcpy_P(char *dest, PGM_P src)', desc: 'Copies a flash string into a RAM buffer.' },
            { name: 'strncpy_P', signature: 'char *strncpy_P(char *dest, PGM_P src, size_t n)', desc: 'Copies at most n bytes of a flash string into a RAM buffer.' },
            { name: 'strcat_P', signature: 'char *strcat_P(char *dest, PGM_P src)', desc: 'Appends a flash string to a RAM string.' },
            { name: 'strncat_P', signature: 'char *strncat_P(char *dest, PGM_P src, size_t n)', desc: 'Appends at most n bytes of a flash string to a RAM string.' },
            { name: 'strcmp_P', signature: 'int strcmp_P(const char *s1, PGM_P s2)', desc: 'Compares a RAM string with a flash string.' },
            { name: 'strncmp_P', signature: 'int strncmp_P(const char *s1, PGM_P s2, size_t n)', desc: 'Compares at most n bytes of a RAM and a flash string.' },
            { name: 'strcasecmp_P', signature: 'int strcasecmp_P(const char *s1, PGM_P s2)', desc: 'Case-insensitive comparison of a RAM and a flash string.' },
            { name: 'strncasecmp_P', signature: 'int strncasecmp_P(const char *s1, PGM_P s2, size_t n)', desc: 'Case-insensitive comparison of at most n bytes of a RAM and a flash string.' },
            { name: 'strstr_P', signature: 'char *strstr_P(const char *s1, PGM_P s2)', desc: 'Locates the first occurrence of a flash substring inside a RAM string.' },
            { name: 'strchr_P', signature: 'const char *strchr_P(PGM_P s, int __val)', desc: 'Locates the first occurrence of a character in a flash string.' },
            { name: 'strrchr_P', signature: 'const char *strrchr_P(PGM_P s, int __val)', desc: 'Locates the last occurrence of a character in a flash string.' },
            { name: 'strlen_P', signature: 'size_t strlen_P(PGM_P s)', desc: 'Returns the length of a flash string (inline, constant-folded when possible).' },
            { name: 'strnlen_P', signature: 'size_t strnlen_P(PGM_P s, size_t len)', desc: 'Returns the length of a flash string, at most len.' },
            { name: 'strlcpy_P', signature: 'size_t strlcpy_P(char *dst, PGM_P src, size_t siz)', desc: 'Safe bounded copy of a flash string into a RAM buffer.' },
            { name: 'strlcat_P', signature: 'size_t strlcat_P(char *dst, PGM_P src, size_t siz)', desc: 'Safe bounded append of a flash string to a RAM buffer.' },
            { name: 'memcpy_P', signature: 'void *memcpy_P(void *dest, PGM_VOID_P src, size_t n)', desc: 'Copies n bytes from flash to RAM.' },
            { name: 'memcmp_P', signature: 'int memcmp_P(const void *s1, PGM_VOID_P s2, size_t n)', desc: 'Compares n bytes of RAM with flash.' },
            { name: 'memchr_P', signature: 'const void *memchr_P(PGM_VOID_P s, int __val, size_t len)', desc: 'Scans n bytes of flash for a byte value.' },
        ],
        macros: [
            { name: 'PROGMEM', desc: 'Variable attribute that places a const object in the .progmem flash section (const char s[] PROGMEM = "…";).' },
            { name: 'PSTR(s)', desc: 'Stores a string literal in flash and returns a pointer to it (for use within one function).' },
            { name: 'PGM_P', desc: 'Type alias for a pointer to a flash string (const char *).' },
            { name: 'pgm_read_byte_near(address_short)', desc: 'Reads one byte from flash with a 16-bit near address (what pgm_read_byte maps to).' },
            { name: 'pgm_read_word_near(address_short)', desc: 'Reads a 16-bit word from flash with a 16-bit near address (_dword/_float/_ptr near variants exist too).' },
            { name: '__flash', desc: 'Named address-space qualifier (avr-gcc extension): const __flash uint8_t t[] = …; is read with plain C syntax.' },
            { name: '__flash1 … __flash5', desc: 'Named address spaces for flash windows above 64 KiB on devices with RAMPZ (avr-gcc extension).' },
            { name: '__memx', desc: '24-bit generic address-space qualifier for pointers that may target RAM or flash (avr-gcc extension).' },
            { name: '__eeprom', desc: 'Named address-space qualifier for EEPROM pointers that are dereferenced directly (avr-gcc extension).' },
        ],
        notes: 'Put string literals and lookup tables in flash: const uint8_t tbl[] PROGMEM = {…}; then read with pgm_read_byte(&tbl[i]) or declare const __flash and skip the macros. printf-family functions with flash format strings (printf_P, puts_P …) are declared in <stdio.h>. On parts above 64 KiB prefer the __flash named address spaces — the legacy pgm_read_*_far / *_PF API still exists in avr-libc 2.x but is deprecated. __flash/__flash1-5/__memx/__eeprom are compiler extensions (avr-gcc 4.6+), not avr-libc macros.',
    },
    {
        id: 'power',
        header: 'avr/power.h',
        summary: 'Peripheral clock gating in the PRR to cut idle power, plus the system clock prescaler.',
        include: '#include <avr/power.h>',
        functions: [
            { name: 'power_adc_enable', signature: 'void power_adc_enable(void)', desc: 'Re-enables the ADC clock (clears the PRADC bit in PRR).' },
            { name: 'power_adc_disable', signature: 'void power_adc_disable(void)', desc: 'Shuts off the ADC clock to save power.' },
            { name: 'power_spi_enable', signature: 'void power_spi_enable(void)', desc: 'Re-enables the SPI clock.' },
            { name: 'power_spi_disable', signature: 'void power_spi_disable(void)', desc: 'Shuts off the SPI clock.' },
            { name: 'power_usart0_enable', signature: 'void power_usart0_enable(void)', desc: 'Re-enables the USART0 clock.' },
            { name: 'power_usart0_disable', signature: 'void power_usart0_disable(void)', desc: 'Shuts off the USART0 clock.' },
            { name: 'power_usart1_enable', signature: 'void power_usart1_enable(void)', desc: 'Re-enables the USART1 clock (devices with two USARTs).' },
            { name: 'power_usart1_disable', signature: 'void power_usart1_disable(void)', desc: 'Shuts off the USART1 clock (devices with two USARTs).' },
            { name: 'power_timer0_enable', signature: 'void power_timer0_enable(void)', desc: 'Re-enables the Timer0 clock.' },
            { name: 'power_timer0_disable', signature: 'void power_timer0_disable(void)', desc: 'Shuts off the Timer0 clock.' },
            { name: 'power_timer1_enable', signature: 'void power_timer1_enable(void)', desc: 'Re-enables the Timer1 clock.' },
            { name: 'power_timer1_disable', signature: 'void power_timer1_disable(void)', desc: 'Shuts off the Timer1 clock.' },
            { name: 'power_twi_enable', signature: 'void power_twi_enable(void)', desc: 'Re-enables the TWI (I2C) clock.' },
            { name: 'power_twi_disable', signature: 'void power_twi_disable(void)', desc: 'Shuts off the TWI (I2C) clock.' },
            { name: 'power_usb_enable', signature: 'void power_usb_enable(void)', desc: 'Re-enables the USB controller clock (USB-capable devices like ATmega32U4).' },
            { name: 'power_usb_disable', signature: 'void power_usb_disable(void)', desc: 'Shuts off the USB controller clock (USB-capable devices).' },
            { name: 'power_all_enable', signature: 'void power_all_enable(void)', desc: 'Re-enables every gateable peripheral clock at once.' },
            { name: 'power_all_disable', signature: 'void power_all_disable(void)', desc: 'Shuts off every gateable peripheral clock at once (biggest idle saving short of sleeping).' },
            { name: 'clock_prescale_set', signature: 'void clock_prescale_set(clock_div_t __x)', desc: 'Sets the system clock prescaler through the CCP-protected CLKPR register.' },
            { name: 'clock_prescale_get', signature: 'clock_div_t clock_prescale_get(void)', desc: 'Reads the current prescaler setting from CLKPR (macro).' },
        ],
        macros: [
            { name: 'clock_div_1', desc: 'clock_div_t value: divide the system clock by 1.' },
            { name: 'clock_div_2', desc: 'clock_div_t value: divide the system clock by 2.' },
            { name: 'clock_div_4', desc: 'clock_div_t value: divide the system clock by 4.' },
            { name: 'clock_div_8', desc: 'clock_div_t value: divide the system clock by 8.' },
            { name: 'clock_div_16', desc: 'clock_div_t value: divide the system clock by 16.' },
            { name: 'clock_div_32', desc: 'clock_div_t value: divide the system clock by 32.' },
            { name: 'clock_div_64', desc: 'clock_div_t value: divide the system clock by 64.' },
            { name: 'clock_div_128', desc: 'clock_div_t value: divide the system clock by 128.' },
            { name: 'clock_div_256', desc: 'clock_div_t value: divide the system clock by 256.' },
        ],
        notes: 'Each power_xxx function only exists on devices that really have that peripheral (the header selects the set per MCU — XMEGA provides a much larger per-module list). Note that disabling a peripheral clock makes its registers unreadable; call the enable function before using the peripheral again.',
    },
    {
        id: 'sfr',
        header: 'avr/sfr_defs.h',
        summary: 'Low-level special-function-register access macros — pulled in automatically by avr/io.h.',
        include: '#include <avr/io.h>  // avr/sfr_defs.h comes with it',
        functions: [
            { name: '(legacy macros)', signature: 'sbi(port, bit), cbi(port, bit), inp(port), outp(val, port), inb(port), outb(val, port)', desc: 'Deprecated legacy register macros from old avr-libc releases — in avr-libc 2.x they live only in <compat/deprecated.h>.' },
        ],
        macros: [
            { name: '_BV(bit)', desc: 'Creates a bitmask (1 << bit).' },
            { name: '_SFR_IO8(io_addr)', desc: 'Declares an 8-bit register at an I/O-mapped address (used by the ioXXXX.h headers).' },
            { name: '_SFR_IO16(io_addr)', desc: 'Declares a 16-bit register at an I/O-mapped address.' },
            { name: '_SFR_MEM8(mem_addr)', desc: 'Declares an 8-bit register at an extended memory-mapped address.' },
            { name: '_SFR_MEM16(mem_addr)', desc: 'Declares a 16-bit register at an extended memory-mapped address.' },
            { name: '_SFR_MEM32(mem_addr)', desc: 'Declares a 32-bit register at an extended memory-mapped address.' },
            { name: '_SFR_IO_ADDR(sfr)', desc: 'Returns the 6-bit I/O address of a register, for use with the out/in instructions.' },
            { name: '_SFR_MEM_ADDR(sfr)', desc: 'Returns the 16-bit memory-mapped address of a register.' },
        ],
        notes: 'These macros are what the device headers use to define every register. The classic sbi()/cbi()/inp()/outp()/inb()/outb() macros are deprecated — write DDRB |= _BV(2) and PORTA = value directly instead; include <compat/deprecated.h> only for porting ancient code.',
    },
    {
        id: 'delay',
        header: 'util/delay.h',
        summary: 'Calibrated busy-wait delays in milliseconds and microseconds.',
        include: '#include <util/delay.h>',
        functions: [
            { name: '_delay_ms', signature: 'void _delay_ms(double __ms)', desc: 'Busy-waits __ms milliseconds; F_CPU must be defined at compile time.' },
            { name: '_delay_us', signature: 'void _delay_us(double __us)', desc: 'Busy-waits __us microseconds; F_CPU must be defined at compile time.' },
        ],
        macros: [],
        notes: 'F_CPU (in Hz) must be known at compile time (-DF_CPU=16000000UL); otherwise the header warns and falls back to 1 MHz (the documented "vanilla" fallback). Maximal delay is 262.14 ms / F_CPU_in_MHz for _delay_ms() and 768 µs / F_CPU_in_MHz for _delay_us(); with __builtin_avr_delay_cycles() support (every modern avr-gcc) it is 4294967.295 ms resp. µs / F_CPU_in_MHz. Over-limit _delay_ms() degrades to 1/10 ms resolution (up to 6.5535 s) or overflows to 0 ms; over-limit _delay_us() automatically falls back to _delay_ms(). Cycle counts round UP by default; define __DELAY_ROUND_DOWN__ or __DELAY_ROUND_CLOSEST__ before the include to change that. Optimizations must be enabled (release -Os, debug -Og both qualify) and the delay must be a compile-time constant — otherwise the delay is much longer and pulls in the floating-point library.',
    },
    {
        id: 'delay_basic',
        header: 'util/delay_basic.h',
        summary: 'Raw cycle-exact busy-loops that <util/delay.h> builds upon.',
        include: '#include <util/delay_basic.h>',
        functions: [
            { name: '_delay_loop_1', signature: 'void _delay_loop_1(uint8_t __count)', desc: '8-bit busy-loop taking 3 CPU cycles per iteration (768 cycles at most).' },
            { name: '_delay_loop_2', signature: 'void _delay_loop_2(uint16_t __count)', desc: '16-bit busy-loop taking 4 CPU cycles per iteration (262144 cycles at most).' },
        ],
        macros: [],
        notes: 'Building blocks for hand-computed cycle delays; prefer _delay_ms()/_delay_us() from <util/delay.h> which convert time to loop counts for you.',
    },
    {
        id: 'atomic',
        header: 'util/atomic.h',
        summary: 'Blocks that disable interrupts for a stretch of code and restore them afterwards.',
        include: '#include <util/atomic.h>',
        functions: [],
        macros: [
            { name: 'ATOMIC_BLOCK(type)', desc: 'For-loop construct that executes cli() on entry and sei() on exit of the block body.' },
            { name: 'ATOMIC_RESTORESTATE', desc: 'ATOMIC_BLOCK parameter that restores the previous SREG I-bit state when leaving the block.' },
            { name: 'ATOMIC_FORCEON', desc: 'ATOMIC_BLOCK parameter that always re-enables interrupts (sei) when leaving the block.' },
            { name: 'NONATOMIC_BLOCK(type)', desc: 'Inverse construct: temporarily re-enables interrupts inside an otherwise critical region.' },
            { name: 'NONATOMIC_RESTORESTATE', desc: 'NONATOMIC_BLOCK parameter restoring the previous interrupt state afterwards.' },
            { name: 'NONATOMIC_FORCEOFF', desc: 'NONATOMIC_BLOCK parameter that disables interrupts again when leaving.' },
        ],
        notes: 'Wrap multi-step accesses to data shared with ISRs, e.g. reading a 16-bit timer: ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { t = TCNT1; }. The compiler guarantees the sei/restore even when the block is left via break or continue.',
    },
    {
        id: 'crc16',
        header: 'util/crc16.h',
        summary: 'Optimised assembler CRC-16 update helpers for three common polynomials.',
        include: '#include <util/crc16.h>',
        functions: [
            { name: '_crc16_update', signature: 'uint16_t _crc16_update(uint16_t __crc, uint8_t __data)', desc: 'Feeds one byte into a CRC-16 with reversed polynomial 0xA001.' },
            { name: '_crc_xmodem_update', signature: 'uint16_t _crc_xmodem_update(uint16_t __crc, uint8_t __data)', desc: 'Feeds one byte into a CRC-16/XMODEM with polynomial 0x1021.' },
            { name: '_crc_ccitt_update', signature: 'uint16_t _crc_ccitt_update(uint16_t __crc, uint8_t __data)', desc: 'Feeds one byte into a reflected CCITT CRC-16 with polynomial 0x8408.' },
        ],
        macros: [],
        notes: 'Start with the CRC seed required by your protocol (usually 0 or 0xFFFF) and pass every byte through the update function; the return value is the running checksum.',
    },
    {
        id: 'parity',
        header: 'util/parity.h',
        summary: 'Single-instruction-parity computation for a byte value.',
        include: '#include <util/parity.h>',
        functions: [],
        macros: [
            { name: 'parity_even_bit(val)', desc: 'Computes the even parity of a byte: returns 1 if val has an odd number of bits set (inline-asm macro).' },
        ],
        notes: 'Only even parity is provided; odd parity is simply !parity_even_bit(val). The macro evaluates its argument multiple times, so pass a plain variable.',
    },
    {
        id: 'twi',
        header: 'util/twi.h',
        summary: 'Bit patterns and status codes for the two-wire interface (I2C) of classic megaAVR devices.',
        include: '#include <util/twi.h>',
        functions: [],
        macros: [
            { name: 'TW_STATUS', desc: 'Evaluates to (TWSR & TW_STATUS_MASK): the current 5-bit TWI status code.' },
            { name: 'TW_STATUS_MASK', desc: 'Mask that extracts the status code bits from TWSR.' },
            { name: 'TW_READ', desc: 'Bit value (1) for the R/W bit in a SLA+R (read) address byte.' },
            { name: 'TW_WRITE', desc: 'Bit value (0) for the R/W bit in a SLA+W (write) address byte.' },
            { name: 'TW_START', desc: 'Status code 0x08: START condition transmitted.' },
            { name: 'TW_REP_START', desc: 'Status code 0x10: repeated START transmitted.' },
            { name: 'TW_MT_SLA_ACK', desc: 'Status code 0x18: SLA+W transmitted, ACK received.' },
            { name: 'TW_MR_SLA_ACK', desc: 'Status code 0x40: SLA+R transmitted, ACK received.' },
            { name: 'TW_NO_INFO', desc: 'Status code 0xF8: no relevant state information available.' },
            { name: 'TW_BUS_ERROR', desc: 'Status code 0x00: illegal START or STOP condition detected.' },
        ],
        notes: 'The header defines the complete master/transmitter/receiver and slave status set (TW_MT_*, TW_MR_*, TW_ST_*, TW_SR_*). Note: TW_ACK / TW_NO_ACK masks shown in some tutorials are NOT part of avr-libc — set the TWINT/TWEA bits in TWCR yourself.',
    },
    {
        id: 'setbaud',
        header: 'util/setbaud.h',
        summary: 'Preprocessor-computed UBRR values for the UART baud rate generator.',
        include: '#include <util/setbaud.h>',
        functions: [],
        macros: [
            { name: 'UBRR_VALUE', desc: 'The UBRR prescaler value computed from F_CPU and BAUD.' },
            { name: 'UBRRL_VALUE', desc: 'Low byte of UBRR_VALUE, for the UBRRL register.' },
            { name: 'UBRRH_VALUE', desc: 'High byte of UBRR_VALUE, for the UBRRH register.' },
            { name: 'USE_2X', desc: '1 if the U2X double-speed bit must be set to hit the requested baud within tolerance, else 0.' },
            { name: 'BAUD_TOL', desc: 'Acceptable baud rate tolerance in percent; defaults to 2 and may be defined before including.' },
        ],
        notes: 'F_CPU and BAUD must be defined before the #include — everything is worked out by the preprocessor, then: UBRRH = UBRRH_VALUE; UBRRL = UBRRL_VALUE; #if USE_2X … set/clear U2X. The header can be included several times with different BAUD values (#undef BAUD in between).',
    },
    {
        id: 'boot',
        header: 'avr/boot.h',
        summary: 'Flash self-programming (SPM) API for boot loaders.',
        include: '#include <avr/boot.h>',
        functions: [
            { name: 'boot_page_erase', signature: 'void boot_page_erase(uint32_t address)', desc: 'Erases one flash page (SPM_PAGESIZE bytes) at the byte address.' },
            { name: 'boot_page_fill', signature: 'void boot_page_fill(uint32_t address, uint16_t data)', desc: 'Loads one little-endian word into the SPM temporary page buffer.' },
            { name: 'boot_page_write', signature: 'void boot_page_write(uint32_t address)', desc: 'Writes the temporary page buffer into flash at the byte address.' },
            { name: 'boot_rww_enable', signature: 'void boot_rww_enable(void)', desc: 'Re-enables the read-while-write (RWW) flash section after programming so the application can run again.' },
            { name: 'boot_spm_busy_wait', signature: 'void boot_spm_busy_wait(void)', desc: 'Spins until the current SPM operation has completed.' },
            { name: 'boot_spm_busy', signature: 'uint8_t boot_spm_busy(void)', desc: 'Tests whether an SPM operation is still in progress.' },
            { name: 'boot_rww_busy', signature: 'uint8_t boot_rww_busy(void)', desc: 'Tests whether the RWW section is still busy.' },
            { name: 'boot_spm_interrupt_enable', signature: 'void boot_spm_interrupt_enable(void)', desc: 'Enables the SPM-ready interrupt in the SPM control register.' },
            { name: 'boot_spm_interrupt_disable', signature: 'void boot_spm_interrupt_disable(void)', desc: 'Disables the SPM-ready interrupt.' },
            { name: 'boot_lock_bits_set', signature: 'void boot_lock_bits_set(uint8_t lock_bits)', desc: 'Sets the flash lock bits with an SPM sequence — irreversible in-circuit, use with extreme care.' },
            { name: 'boot_signature_byte_get', signature: 'uint8_t boot_signature_byte_get(uint_farptr_t address)', desc: 'Reads a signature or oscillator-calibration byte by address.' },
        ],
        macros: [
            { name: 'BOOTLOADER_SECTION', desc: 'Attribute placing code into the .bootloader section (combine with a linker option like -section-start=.bootloader=0x1F800).' },
        ],
        notes: 'SPM self-programming only works when executed from the (N)RWW boot loader section. Typical sequence: save SREG + cli; eeprom_busy_wait(); boot_page_erase(addr); boot_spm_busy_wait(); fill words with boot_page_fill(addr+i, w); boot_page_write(addr); boot_spm_busy_wait(); boot_rww_enable(); restore SREG. The _safe variants (boot_page_erase_safe etc.) wrap this with the busy-waits and interrupt disable automatically.',
    },
    {
        id: 'cpufunc',
        header: 'avr/cpufunc.h',
        summary: 'Two tiny CPU helpers: a guaranteed nop and a compiler memory barrier.',
        include: '#include <avr/cpufunc.h>',
        functions: [],
        macros: [
            { name: '_NOP()', desc: 'Emits exactly one nop instruction that the compiler cannot optimize away.' },
            { name: '_MemoryBarrier()', desc: 'Compiler-only memory barrier (empty asm with a "memory" clobber) that orders volatile and non-volatile accesses.' },
        ],
        notes: 'Neither macro has run-time cost beyond the nop; _MemoryBarrier() only constrains code generation, useful around DMA/peripheral buffer access.',
    },
    {
        id: 'fuse',
        header: 'avr/fuse.h',
        summary: 'Compile-time fuse-bit definition stored in the .fuse section of the ELF file.',
        include: '#include <avr/fuse.h>  // via <avr/io.h>',
        functions: [
            { name: '(struct __fuse_t)', signature: 'struct __fuse_t { unsigned char low, high, extended; }', desc: 'Fuse byte structure of classic devices; XMEGA/newer parts use byte[] or NVM_FUSES_t — the fields come from the device header.' },
        ],
        macros: [
            { name: 'FUSES', desc: 'Expands to "__fuse_t __fuse" in the .fuse section so FUSES = { .low = …, .high = …, .extended = … }; defines all fuses at once.' },
            { name: 'FUSEMEM', desc: 'The raw __used__/section(".fuse") attribute behind FUSES.' },
            { name: 'LFUSE_DEFAULT', desc: 'Device-specific factory default for the low fuse byte.' },
            { name: 'HFUSE_DEFAULT', desc: 'Device-specific factory default for the high fuse byte.' },
            { name: 'EFUSE_DEFAULT', desc: 'Device-specific factory default for the extended fuse byte.' },
        ],
        notes: 'Fuse bits are active-low and combined with & (bitwise AND), e.g. .high = (FUSE_BOOTSZ0 & FUSE_BOOTSZ1 & FUSE_EESAVE & FUSE_SPIEN). Every field MUST be initialized — use the *_DEFAULT macros. Inspect with avr-objdump -s -j .fuse firmware.elf, then program the values with avrdude -U lfuse/hfuse/efuse:….',
    },
    {
        id: 'lock',
        header: 'avr/lock.h',
        summary: 'Compile-time lock-bits definition stored in the .lock section of the ELF file.',
        include: '#include <avr/lock.h>  // via <avr/io.h>',
        functions: [],
        macros: [
            { name: 'LOCKBITS', desc: 'Expands to "unsigned char __lock" in the .lock section so LOCKBITS = (LB_MODE_1 & BLB0_MODE_3); sets the lock byte.' },
            { name: 'LOCKMEM', desc: 'The raw __used__/section(".lock") attribute behind LOCKBITS.' },
            { name: 'LOCKBITS_DEFAULT', desc: 'Default unprogrammed lock byte value (0xFF).' },
            { name: 'LB_MODE_n / BLB0_MODE_n / BLB1_MODE_n', desc: 'Lock-bit mode masks from the device header (n = 1…3 for LB, 1…4 for the boot-lock BLBx bits).' },
        ],
        notes: 'Lock bits are active-low — combine the mode macros with &. ALWAYS initialise the lock byte, even with LOCKBITS_DEFAULT: an uninitialised 0 could lock the chip to an unrecoverable state. Verify with avr-objdump -s -j .lock firmware.elf; lock bits only clear again through a chip erase.',
    },
    {
        id: 'stdio',
        header: 'stdio.h',
        summary: 'The full avr-libc stream I/O layer: FILE streams over device callbacks, printf/scanf families and their _P flash variants.',
        include: '#include <stdio.h>',
        functions: [
            { name: 'fdevopen', signature: 'FILE *fdevopen(int (*put)(char, FILE *), int (*get)(FILE *))', desc: 'Opens a stream over user put/get callback functions and wires it to stdin/stdout/stderr (allocates a FILE).' },
            { name: 'fdev_setup_stream', signature: 'void fdev_setup_stream(FILE *stream, int (*put)(char, FILE *), int (*get)(FILE *), int rwflag)', desc: 'Macro that initialises a user-supplied static FILE with the callbacks and _FDEV_SETUP_* mode — no malloc needed.' },
            { name: 'fclose', signature: 'int fclose(FILE *__stream)', desc: 'Closes a stream opened by fdevopen() and frees the FILE structure.' },
            { name: 'printf', signature: 'int printf(const char *__fmt, …)', desc: 'Formatted output to stdout.' },
            { name: 'printf_P', signature: 'int printf_P(const char *__fmt, …)', desc: 'printf() with the format string residing in flash (combine with PSTR()).' },
            { name: 'fprintf', signature: 'int fprintf(FILE *__stream, const char *__fmt, …)', desc: 'Formatted output to any stream.' },
            { name: 'fprintf_P', signature: 'int fprintf_P(FILE *__stream, const char *__fmt, …)', desc: 'fprintf() with the format string in flash.' },
            { name: 'vprintf', signature: 'int vprintf(const char *__fmt, va_list __ap)', desc: 'printf() taking arguments from a va_list.' },
            { name: 'vfprintf', signature: 'int vfprintf(FILE *__stream, const char *__fmt, va_list __ap)', desc: 'The core formatter every printf-family function funnels through.' },
            { name: 'vfprintf_P', signature: 'int vfprintf_P(FILE *__stream, const char *__fmt, va_list __ap)', desc: 'vfprintf() with the format string in flash.' },
            { name: 'sprintf', signature: 'int sprintf(char *__s, const char *__fmt, …)', desc: 'Formatted output into a RAM string buffer.' },
            { name: 'sprintf_P', signature: 'int sprintf_P(char *__s, const char *__fmt, …)', desc: 'sprintf() with the format string in flash.' },
            { name: 'snprintf', signature: 'int snprintf(char *__s, size_t __n, const char *__fmt, …)', desc: 'Bounded sprintf() that never writes more than __n bytes.' },
            { name: 'snprintf_P', signature: 'int snprintf_P(char *__s, size_t __n, const char *__fmt, …)', desc: 'snprintf() with the format string in flash.' },
            { name: 'vsprintf_P', signature: 'int vsprintf_P(char *__s, const char *__fmt, va_list ap)', desc: 'sprintf_P() taking a va_list.' },
            { name: 'vsnprintf_P', signature: 'int vsnprintf_P(char *__s, size_t __n, const char *__fmt, va_list ap)', desc: 'snprintf_P() taking a va_list.' },
            { name: 'puts', signature: 'int puts(const char *__str)', desc: 'Writes a string plus newline to stdout.' },
            { name: 'puts_P', signature: 'int puts_P(const char *__str)', desc: 'puts() with the string in flash.' },
            { name: 'putchar', signature: 'int putchar(int __c)', desc: 'Writes a single character to stdout.' },
            { name: 'fputs', signature: 'int fputs(const char *__str, FILE *__stream)', desc: 'Writes a string (no newline) to a stream.' },
            { name: 'fputs_P', signature: 'int fputs_P(const char *__str, FILE *__stream)', desc: 'fputs() with the string in flash.' },
            { name: 'fgetc', signature: 'int fgetc(FILE *__stream)', desc: 'Reads one character from a stream.' },
            { name: 'getc', signature: 'int getc(FILE *__stream)', desc: 'Alias of fgetc().' },
            { name: 'getchar', signature: 'int getchar(void)', desc: 'Reads one character from stdin.' },
            { name: 'ungetc', signature: 'int ungetc(int __c, FILE *__stream)', desc: 'Pushes one character back onto the input stream.' },
            { name: 'fgets', signature: 'char *fgets(char *__str, int __size, FILE *__stream)', desc: 'Reads a line (bounded) from a stream.' },
            { name: 'gets', signature: 'char *gets(char *__str)', desc: 'Reads a line from stdin with no bound — inherently unsafe, prefer fgets().' },
            { name: 'fread', signature: 'size_t fread(void *__ptr, size_t __size, size_t __nmemb, FILE *__stream)', desc: 'Reads nmemb elements into a RAM array.' },
            { name: 'fwrite', signature: 'size_t fwrite(const void *__ptr, size_t __size, size_t __nmemb, FILE *__stream)', desc: 'Writes nmemb elements from a RAM array to a stream.' },
            { name: 'feof', signature: 'int feof(FILE *__stream)', desc: 'Tests the end-of-file indicator of a stream.' },
            { name: 'ferror', signature: 'int ferror(FILE *__stream)', desc: 'Tests the error indicator of a stream.' },
            { name: 'clearerr', signature: 'void clearerr(FILE *__stream)', desc: 'Clears the error and EOF indicators of a stream.' },
            { name: 'fflush', signature: 'int fflush(FILE *__stream)', desc: 'Flushes buffered output of a stream (a no-op for unbuffered device streams).' },
            { name: 'scanf', signature: 'int scanf(const char *__fmt, …)', desc: 'Formatted input from stdin.' },
            { name: 'scanf_P', signature: 'int scanf_P(const char *__fmt, …)', desc: 'scanf() with the format string in flash.' },
            { name: 'sscanf', signature: 'int sscanf(const char *__buf, const char *__fmt, …)', desc: 'Formatted input parsed from a RAM string.' },
            { name: 'sscanf_P', signature: 'int sscanf_P(const char *__buf, const char *__fmt, …)', desc: 'sscanf() with the format string in flash (fscanf/fscanf_P/vfscanf_P also exist).' },
        ],
        macros: [
            { name: 'stdin', desc: 'Standard input stream (initially bound to the first fdevopen() get-side stream).' },
            { name: 'stdout', desc: 'Standard output stream — what printf()/puts() write to.' },
            { name: 'stderr', desc: 'Standard error stream; assert() reports here.' },
            { name: 'FDEV_SETUP_STREAM(put, get, rwflag)', desc: 'Declarative variant of fdev_setup_stream() for initialising a static FILE at definition time.' },
            { name: '_FDEV_SETUP_READ', desc: 'rwflag value: stream is opened for reading.' },
            { name: '_FDEV_SETUP_WRITE', desc: 'rwflag value: stream is opened for writing.' },
            { name: '_FDEV_SETUP_RW', desc: 'rwflag value: stream is opened for reading and writing.' },
            { name: 'fdev_set_udata(stream, u)', desc: 'Stores a user data pointer in the FILE for the put/get callbacks to fetch.' },
            { name: 'fdev_get_udata(stream)', desc: 'Retrieves the user data pointer previously stored in the FILE.' },
            { name: 'EOF', desc: 'End-of-file marker returned by input functions (-1).' },
        ],
        notes: 'There is no OS — wire a UART first: stdout = fdevopen(uart_putchar, NULL); or declare static FILE mystdout = FDEV_SETUP_STREAM(uart_putchar, NULL, _FDEV_SETUP_WRITE); stdout = &mystdout;. The default vfprintf handles integers/strings only; for %f link -Wl,-u,vfprintf -lprintf_flt -lm (scanf floats: -Wl,-u,vfscanf -lscanf_flt -lm; smallest code: -Wl,-u,vfprintf -lprintf_min). The _P variants read their format string from flash via PSTR().',
    },
    {
        id: 'stdlib',
        header: 'stdlib.h',
        summary: 'Conversions, pseudo-random numbers, dynamic memory, sorting/searching — plus avr-libc itoa/dtostre extras.',
        include: '#include <stdlib.h>',
        functions: [
            { name: 'atoi', signature: 'int atoi(const char *__s)', desc: 'Converts a decimal string to an int.' },
            { name: 'atol', signature: 'long atol(const char *__s)', desc: 'Converts a decimal string to a long.' },
            { name: 'strtol', signature: 'long strtol(const char *__nptr, char **__endptr, int __base)', desc: 'Converts a string in the given base (2…36) to a long, reporting the end pointer.' },
            { name: 'strtoul', signature: 'unsigned long strtoul(const char *__nptr, char **__endptr, int __base)', desc: 'Unsigned variant of strtol().' },
            { name: 'strtod', signature: 'double strtod(const char *__nptr, char **__endptr)', desc: 'Converts a string to a double.' },
            { name: 'rand', signature: 'int rand(void)', desc: 'Returns the next pseudo-random number in the range 0…RAND_MAX.' },
            { name: 'srand', signature: 'void srand(unsigned int __seed)', desc: 'Seeds the rand() generator.' },
            { name: 'malloc', signature: 'void *malloc(size_t __size)', desc: 'Allocates __size bytes from the heap, returning NULL when out of memory.' },
            { name: 'calloc', signature: 'void *calloc(size_t __nele, size_t __size)', desc: 'Allocates and zeroes an array of nele elements.' },
            { name: 'realloc', signature: 'void *realloc(void *__ptr, size_t __size)', desc: 'Grows or shrinks a heap block, possibly moving it.' },
            { name: 'free', signature: 'void free(void *__ptr)', desc: 'Returns a heap block to the allocator (free(NULL) is a safe no-op).' },
            { name: 'abort', signature: 'void abort(void)', desc: 'Aborts the program with no cleanup (ends in an infinite loop).' },
            { name: 'exit', signature: 'void exit(int __code)', desc: 'Runs registered atexit() handlers and then stops in an infinite loop.' },
            { name: 'abs', signature: 'int abs(int __i)', desc: 'Returns the absolute value of an int (builtin).' },
            { name: 'labs', signature: 'long labs(long __i)', desc: 'Returns the absolute value of a long (builtin).' },
            { name: 'div', signature: 'div_t div(int __num, int __denom)', desc: 'Computes quotient and remainder of an int division at once.' },
            { name: 'ldiv', signature: 'ldiv_t ldiv(long __num, long __denom)', desc: 'Computes quotient and remainder of a long division at once.' },
            { name: 'qsort', signature: 'void qsort(void *__base, size_t __nmemb, size_t __size, __compar_fn_t __compar)', desc: 'Sorts an array in RAM using the comparison callback.' },
            { name: 'bsearch', signature: 'void *bsearch(const void *__key, const void *__base, size_t __nmemb, size_t __size, __compar_fn_t __compar)', desc: 'Binary-searches a sorted array for a matching element.' },
            { name: 'itoa', signature: 'char *itoa(int __val, char *__s, int __radix)', desc: 'Converts an int to a string in the given radix (avr-libc extension).' },
            { name: 'ltoa', signature: 'char *ltoa(long __val, char *__s, int __radix)', desc: 'Converts a long to a string in the given radix (avr-libc extension).' },
            { name: 'utoa', signature: 'char *utoa(unsigned int val, char *s, int radix)', desc: 'Converts an unsigned int to a string in the given radix (avr-libc extension).' },
            { name: 'ultoa', signature: 'char *ultoa(unsigned long __val, char *__s, int __radix)', desc: 'Converts an unsigned long to a string in the given radix (avr-libc extension).' },
            { name: 'dtostre', signature: 'char *dtostre(double __val, char *__s, unsigned char __prec, unsigned char __flags)', desc: 'Converts a double to a scientific-notation string with the given precision and DTOSTR_* flags (avr-libc extension).' },
            { name: 'dtostrf', signature: 'char *dtostrf(double __val, signed char __width, unsigned char __prec, char *__s)', desc: 'Converts a double to a fixed-point string with field width and precision (avr-libc extension).' },
        ],
        macros: [
            { name: 'RAND_MAX', desc: 'Maximum value returned by rand() (0x7FFF).' },
            { name: 'EXIT_SUCCESS', desc: 'Exit code 0 for exit().' },
            { name: 'EXIT_FAILURE', desc: 'Exit code 1 for exit().' },
            { name: 'DTOSTR_ALWAYS_SIGN', desc: 'dtostre() flag: emit + or space for positive numbers.' },
            { name: 'DTOSTR_PLUS_SIGN', desc: 'dtostre() flag: emit + rather than a space for positive numbers.' },
            { name: 'DTOSTR_UPPERCASE', desc: 'dtostre() flag: use uppercase E in the exponent.' },
        ],
        notes: 'itoa/ltoa/utoa/ultoa/dtostre/dtostrf are avr-libc extensions (not ISO C) and the cheapest way to turn numbers into text without printf. dtostre/dtostrf need no -lprintf_flt. malloc() carves its heap between __malloc_heap_start and __malloc_heap_end (defaults use .bss bounds — see the avr-libc malloc documentation) and returns NULL when exhausted, so always check. exit()/abort() never return to a loader: they end in a loop.',
    },
    {
        id: 'string',
        header: 'string.h',
        summary: 'RAM string and memory functions, including the avr-libc extensions strupr/strlwr/strrev/ffs.',
        include: '#include <string.h>',
        functions: [
            { name: 'memcpy', signature: 'void *memcpy(void *dest, const void *src, size_t n)', desc: 'Copies n bytes between non-overlapping RAM areas.' },
            { name: 'memmove', signature: 'void *memmove(void *dest, const void *src, size_t n)', desc: 'Copies n bytes, safe for overlapping regions.' },
            { name: 'memset', signature: 'void *memset(void *s, int c, size_t n)', desc: 'Fills n bytes of RAM with the byte value c.' },
            { name: 'memcmp', signature: 'int memcmp(const void *s1, const void *s2, size_t n)', desc: 'Compares n bytes of two RAM areas.' },
            { name: 'memchr', signature: 'void *memchr(const void *s, int c, size_t n)', desc: 'Scans n bytes for the first occurrence of byte c.' },
            { name: 'strcpy', signature: 'char *strcpy(char *dest, const char *src)', desc: 'Copies a RAM string including the terminator.' },
            { name: 'strncpy', signature: 'char *strncpy(char *dest, const char *src, size_t n)', desc: 'Copies at most n bytes of a RAM string.' },
            { name: 'strcat', signature: 'char *strcat(char *dest, const char *src)', desc: 'Appends a RAM string to another.' },
            { name: 'strncat', signature: 'char *strncat(char *dest, const char *src, size_t n)', desc: 'Appends at most n bytes of a RAM string.' },
            { name: 'strcmp', signature: 'int strcmp(const char *s1, const char *s2)', desc: 'Compares two RAM strings.' },
            { name: 'strncmp', signature: 'int strncmp(const char *s1, const char *s2, size_t n)', desc: 'Compares at most n bytes of two RAM strings.' },
            { name: 'strcasecmp', signature: 'int strcasecmp(const char *s1, const char *s2)', desc: 'Case-insensitive string comparison (avr-libc extension).' },
            { name: 'strncasecmp', signature: 'int strncasecmp(const char *s1, const char *s2, size_t n)', desc: 'Bounded case-insensitive string comparison (avr-libc extension).' },
            { name: 'strstr', signature: 'char *strstr(const char *s1, const char *s2)', desc: 'Locates a substring inside a RAM string.' },
            { name: 'strchr', signature: 'char *strchr(const char *s, int c)', desc: 'Locates the first occurrence of a character in a string.' },
            { name: 'strrchr', signature: 'char *strrchr(const char *s, int c)', desc: 'Locates the last occurrence of a character in a string.' },
            { name: 'strchrnul', signature: 'char *strchrnul(const char *s, int c)', desc: 'Like strchr() but returns a pointer to the terminator when not found (GNU extension).' },
            { name: 'strtok', signature: 'char *strtok(char *s, const char *delim)', desc: 'Splits a string into tokens by delimiter characters.' },
            { name: 'strtok_r', signature: 'char *strtok_r(char *s, const char *delim, char **last)', desc: 'Re-entrant variant of strtok().' },
            { name: 'strlen', signature: 'size_t strlen(const char *s)', desc: 'Returns the length of a RAM string.' },
            { name: 'strnlen', signature: 'size_t strnlen(const char *s, size_t len)', desc: 'Returns the length of a string, at most len.' },
            { name: 'strlcpy', signature: 'size_t strlcpy(char *dst, const char *src, size_t siz)', desc: 'Safe bounded string copy that always terminates (BSD-style extension).' },
            { name: 'strlcat', signature: 'size_t strlcat(char *dst, const char *src, size_t siz)', desc: 'Safe bounded string append that always terminates (BSD-style extension).' },
            { name: 'strupr', signature: 'char *strupr(char *s)', desc: 'Converts a string to uppercase in place (avr-libc extension).' },
            { name: 'strlwr', signature: 'char *strlwr(char *s)', desc: 'Converts a string to lowercase in place (avr-libc extension).' },
            { name: 'strrev', signature: 'char *strrev(char *s)', desc: 'Reverses a string in place (avr-libc extension).' },
            { name: 'strsep', signature: 'char *strsep(char **sp, const char *delim)', desc: 'Tokenises a string by delimiter substring, updating the cursor (BSD extension).' },
            { name: 'ffs', signature: 'int ffs(int __val)', desc: 'Returns the 1-based index of the first set bit, or 0 if none.' },
        ],
        macros: [],
        notes: 'The _P suffix variants (strcpy_P, strcmp_P, strlen_P …) are declared in <avr/pgmspace.h> and read their flash-side argument from program memory. strcasecmp/strncasecmp/strlcpy/strlcat/strsep/strchrnul/strupr/strlwr/strrev are avr-libc/BSD/GNU extensions beyond ISO C. strdup() exists but pulls in malloc().',
    },
    {
        id: 'math',
        header: 'math.h',
        summary: 'The avr-libc math library (libm) — trigonometry, exponentials, rounding and helpers.',
        include: '#include <math.h>',
        functions: [
            { name: 'sin', signature: 'double sin(double __x)', desc: 'Sine of an angle in radians.' },
            { name: 'cos', signature: 'double cos(double __x)', desc: 'Cosine of an angle in radians.' },
            { name: 'tan', signature: 'double tan(double __x)', desc: 'Tangent of an angle in radians.' },
            { name: 'asin', signature: 'double asin(double __x)', desc: 'Arc sine; errno becomes EDOM outside [-1, 1].' },
            { name: 'acos', signature: 'double acos(double __x)', desc: 'Arc cosine; errno becomes EDOM outside [-1, 1].' },
            { name: 'atan', signature: 'double atan(double __x)', desc: 'Arc tangent of a value.' },
            { name: 'atan2', signature: 'double atan2(double __y, double __x)', desc: 'Arc tangent of y/x using the signs of both to pick the quadrant.' },
            { name: 'sinh', signature: 'double sinh(double __x)', desc: 'Hyperbolic sine.' },
            { name: 'cosh', signature: 'double cosh(double __x)', desc: 'Hyperbolic cosine.' },
            { name: 'tanh', signature: 'double tanh(double __x)', desc: 'Hyperbolic tangent.' },
            { name: 'exp', signature: 'double exp(double __x)', desc: 'e raised to the power x.' },
            { name: 'log', signature: 'double log(double __x)', desc: 'Natural logarithm; EDOM for negative input.' },
            { name: 'log10', signature: 'double log10(double __x)', desc: 'Base-10 logarithm.' },
            { name: 'pow', signature: 'double pow(double __x, double __y)', desc: 'x raised to the power y.' },
            { name: 'sqrt', signature: 'double sqrt(double __x)', desc: 'Square root; EDOM for negative input (float variant sqrtf exists).' },
            { name: 'cbrt', signature: 'double cbrt(double __x)', desc: 'Cube root.' },
            { name: 'hypot', signature: 'double hypot(double __x, double __y)', desc: 'sqrt(x*x + y*y) without intermediate overflow.' },
            { name: 'square', signature: 'double square(double __x)', desc: 'x * x — avr-libc shortcut cheaper than pow(x, 2).' },
            { name: 'fabs', signature: 'double fabs(double __x)', desc: 'Absolute value of a double (fabsf is an alias).' },
            { name: 'fmod', signature: 'double fmod(double __x, double __y)', desc: 'Floating-point remainder of x/y.' },
            { name: 'modf', signature: 'double modf(double __x, double *__iptr)', desc: 'Splits x into integer and fractional parts (float variant modff exists).' },
            { name: 'floor', signature: 'double floor(double __x)', desc: 'Largest whole number not greater than x.' },
            { name: 'ceil', signature: 'double ceil(double __x)', desc: 'Smallest whole number not less than x.' },
            { name: 'round', signature: 'double round(double __x)', desc: 'Rounds to the nearest whole number, half away from zero.' },
            { name: 'trunc', signature: 'double trunc(double __x)', desc: 'Truncates x towards zero.' },
            { name: 'lround', signature: 'long lround(double __x)', desc: 'Rounds to the nearest long (lrint also exists).' },
            { name: 'frexp', signature: 'double frexp(double __x, int *__pexp)', desc: 'Splits x into mantissa and binary exponent.' },
            { name: 'ldexp', signature: 'double ldexp(double __x, int __exp)', desc: 'Multiplies x by 2 raised to exp.' },
            { name: 'isnan', signature: 'int isnan(double __x)', desc: 'Returns 1 if x is not-a-number.' },
            { name: 'isinf', signature: 'int isinf(double __x)', desc: 'Returns 1 if x is positive infinity (or -1 for negative infinity).' },
            { name: 'isfinite', signature: 'int isfinite(double __x)', desc: 'Returns non-zero if x is neither NaN nor infinity (inline).' },
            { name: 'signbit', signature: 'int signbit(double __x)', desc: 'Returns non-zero if the sign bit of x is set (true for -0.0 too).' },
            { name: 'copysign', signature: 'double copysign(double __x, double __y)', desc: 'Returns x carrying the sign of y (inline).' },
        ],
        macros: [
            { name: 'M_PI', desc: 'The constant pi.' },
            { name: 'M_PI_2', desc: 'pi/2.' },
            { name: 'M_PI_4', desc: 'pi/4.' },
            { name: 'M_E', desc: 'Base of natural logarithms.' },
            { name: 'M_LN2', desc: 'Natural logarithm of 2.' },
            { name: 'M_LN10', desc: 'Natural logarithm of 10.' },
            { name: 'M_LOG10E', desc: 'Base-10 logarithm of e.' },
            { name: 'M_1_PI', desc: '1/pi.' },
            { name: 'M_2_PI', desc: '2/pi.' },
            { name: 'M_SQRT2', desc: 'Square root of 2.' },
            { name: 'M_SQRT1_2', desc: 'Reciprocal square root of 2 (1/sqrt(2)).' },
            { name: 'NAN', desc: 'Float constant representing not-a-number.' },
            { name: 'INFINITY', desc: 'Float constant representing positive infinity.' },
        ],
        notes: 'AVRs have no floating-point unit, so every double operation is software emulation — avoid floats in ISRs and hot loops. Link with -lm (some newer toolchains link libm implicitly). Printing floats with printf additionally needs -Wl,-u,vfprintf -lprintf_flt. isnan/isinf/signbit are real avr-libc functions here, and only modff/sqrtf exist as float variants.',
    },
    {
        id: 'errno',
        header: 'errno.h',
        summary: 'The errno error variable with the two error codes avr-libc actually raises.',
        include: '#include <errno.h>',
        functions: [],
        macros: [
            { name: 'errno', desc: 'Modifiable int lvalue that library functions set on error (extern int errno).' },
            { name: 'EDOM', desc: 'Domain error — a math function was called outside its domain (e.g. sqrt(-1)); value 33.' },
            { name: 'ERANGE', desc: 'Range error — a conversion result does not fit the target type (e.g. strtol); value 34.' },
        ],
        notes: 'Only EDOM and ERANGE are ever set by avr-libc; all other POSIX errno names are defined as no-error placeholders. Clear errno to 0 before the call and test it afterwards — library functions never reset it for you.',
    },
    {
        id: 'stdint',
        header: 'stdint.h / inttypes.h',
        summary: 'Exact-width integer types plus printf/scanf format-string macros.',
        include: '#include <stdint.h>  // #include <inttypes.h> adds the PRI/SCN macros',
        functions: [
            { name: '(fixed-width types)', signature: 'uint8_t, int8_t, uint16_t, int16_t, uint32_t, int32_t, uint64_t, int64_t, uintptr_t, intptr_t', desc: 'Exact-width integer types from <stdint.h> — the portable way to size variables on AVR.' },
        ],
        macros: [
            { name: 'PRId8', desc: 'printf format for int8_t ("d" — inttypes.h).' },
            { name: 'PRIu8', desc: 'printf format for uint8_t ("u" — inttypes.h).' },
            { name: 'PRId16', desc: 'printf format for int16_t ("d").' },
            { name: 'PRIu16', desc: 'printf format for uint16_t ("u").' },
            { name: 'PRId32', desc: 'printf format for int32_t ("ld").' },
            { name: 'PRIu32', desc: 'printf format for uint32_t ("lu").' },
            { name: 'PRIx32', desc: 'printf format for uint32_t in lowercase hex ("lx").' },
            { name: 'PRIdPTR', desc: 'printf format for an intptr_t/pointer-sized signed value.' },
            { name: 'INT8_MAX', desc: 'Largest value of int8_t.' },
            { name: 'UINT8_MAX', desc: 'Largest value of uint8_t.' },
            { name: 'INT16_MAX', desc: 'Largest value of int16_t.' },
            { name: 'UINT16_MAX', desc: 'Largest value of uint16_t.' },
            { name: 'INT32_MAX', desc: 'Largest value of int32_t.' },
            { name: 'UINT32_MAX', desc: 'Largest value of uint32_t.' },
        ],
        notes: 'On AVR an int is 16-bit and a long is 32-bit, so uint32_t must be printed with %lu — printf("%" PRIu32 "\n", v) keeps it portable. <inttypes.h> simply includes <stdint.h> and adds the PRI…/SCN… format macros.',
    },
    {
        id: 'version',
        header: 'avr/version.h',
        summary: 'Compile-time version macros of the avr-libc build in use.',
        include: '#include <avr/version.h>  // also pulled in by <avr/io.h>',
        functions: [],
        macros: [
            { name: '__AVR_LIBC_VERSION_STRING__', desc: 'String literal of the avr-libc version, e.g. "2.0.0".' },
            { name: '__AVR_LIBC_VERSION__', desc: 'Numeric version: major*10000 + minor*100 + revision (20000 for 2.0.0).' },
            { name: '__AVR_LIBC_MAJOR__', desc: 'Major version number.' },
            { name: '__AVR_LIBC_MINOR__', desc: 'Minor version number.' },
            { name: '__AVR_LIBC_REVISION__', desc: 'Revision (patch) number.' },
            { name: '__AVR_LIBC_DATE_STRING__ / __AVR_LIBC_DATE_', desc: 'Release date as "YYYYMMDD" string / numeric value (note the trailing underscore in the numeric one).' },
        ],
        notes: 'Useful for #if feature gates (undefined macros evaluate to 0 in preprocessor expressions, so tests stay portable across very old avr-libc versions).',
    },
    {
        id: 'xmega',
        header: 'avr/xmega.h',
        summary: 'XMEGA-family helper: the configuration-change-protection (CCP) timed write, included automatically by avr/io.h on ATxmega parts.',
        include: '#include <avr/io.h>  // avr/xmega.h comes with it on XMEGA',
        functions: [],
        macros: [
            { name: '_PROTECTED_WRITE(reg, value)', desc: 'Writes value to a CCP-protected I/O register via the timed sequence, e.g. _PROTECTED_WRITE(CLK_CTRL, CLK_SCLKSEL0_bm).' },
        ],
        notes: 'This single macro is all upstream avr-libc provides for XMEGA. The headers <avr/xmega/nvm.h>, <avr/xmega/crc.h> and <avr/xmega/aes.h> sometimes mentioned in tutorials are NOT part of avr-libc 2.x — they ship with Atmel/Microchip XMEGA driver libraries and application notes; EEPROM access on XMEGA still goes through <avr/eeprom.h>.',
    },
    {
        id: 'assert',
        header: 'assert.h',
        summary: 'Runtime assertion macro that aborts with a diagnostic message.',
        include: '#include <assert.h>',
        functions: [],
        macros: [
            { name: 'assert(expression)', desc: 'If the expression evaluates to 0, prints "expression, file, line" to stderr and calls abort().' },
        ],
        notes: 'Define NDEBUG (-DNDEBUG) to compile asserts out — they then expand to ((void)0) and neither the test nor the message costs flash. The failure path needs a working stderr stream to print anything.',
    },
];
const MODULES_COUNT = MODULES.length;
const FUNCTIONS_COUNT = MODULES.reduce((n, m) => n + m.functions.length, 0);
module.exports = { MODULES, MODULES_COUNT, FUNCTIONS_COUNT };
