'use strict';
// XC8 catalogue - data only (no vscode dependencies).
// Reference of Microchip MPLAB XC8 v2.x compiler capabilities for the XC8
// toolchain switch: the unified xc8-cc driver builds for ALL Microchip 8-bit
// devices (PIC10/12/16/18 and AVR ATmega/ATtiny/ATxmega).
// Facts summarised from the Microchip XC8 v2.x compiler documentation.
// Schema (per task B-d): modules carry id/name/include/description plus a
// notes ARRAY of strings; every entry (function or macro) has name/signature/
// description. For the tool-reference modules (driver/devices/install) the
// `include` field carries the command line to run instead of a #include line.
const MODULES = [
  {
    id: 'xc8.xc',
    name: '<xc.h>',
    include: '#include <xc.h>',
    description: 'The universal XC8 device header: pulls in the register, bit and interrupt-vector definitions of the exact device selected with -mcpu=<device>.',
    notes: [
      'One include for every 8-bit target: -mcpu=ATmega328P selects an AVR device header, -mcpu=16F18855 a PIC one.',
      'The SFR register and bit names it defines are the datasheet spellings (PORTA, TRISA, TMR0 on PIC; PORTB, DDRB, TCNT1 on AVR) - always uppercase and always device-specific.',
      'On PIC targets individual bits are commonly reached through the REGbits.BIT structures the device header defines, e.g. PORTAbits.RA0.',
      'Interrupt vector constants used by ISR()/__interrupt() handlers come from the same device header.',
      'Never include a device-specific header directly - xc.h plus -mcpu= is the portable combination that lets one source build for any supported device.',
    ],
    functions: [],
    macros: [
      { name: '(device registers)', signature: 'PORTA, TRISA, TMR0, ADRESH / PORTB, DDRB, TCNT1 ...', description: 'SFR register macros for the device chosen with -mcpu=... - the exact set depends on the part.' },
      { name: '(bit names)', signature: 'RA0, ADGO, GIE / PORTB5, ADSC ...', description: 'Register bit-position names (and the REGbits structures on PIC) defined by the selected device header.' },
      { name: '(vector constants)', signature: 'e.g. TIMER0_OVF_vect, USART_RX_vect (AVR)', description: 'Interrupt vector name constants that ISR()/__interrupt() handlers attach to.' },
    ],
  },
  {
    id: 'xc8.delay',
    name: '_delay_ms / _delay_us',
    include: '#include <util/delay.h>',
    description: 'Busy-wait delays from <util/delay.h> — the avr-libc mechanism XC8-for-AVR uses: F_CPU defines the clock, the functions expand into cycle-counted loops.',
    notes: [
      'F_CPU must be defined as the CPU clock in Hertz (e.g. 16000000UL) — the build passes it as -DF_CPU from the MCU definition; a missing or wrong value silently scales every delay.',
      'The maximal possible delay is 4294967.295 ms / F_CPU in MHz — requesting more overflows and delays 0 us; chain several calls for long waits.',
      'The compiler optimizers must be enabled for accurate delay times (XC8 User Guide 8.4).',
      'Rounding: cycles are rounded UP by default; #define __DELAY_ROUND_DOWN__ or __DELAY_ROUND_CLOSEST__ before including the header to change it.',
      'Delays are blocking busy-waits: interrupts stretch the elapsed time.',
      'NOTE: the PIC-only XC8 constructs _XTAL_FREQ / __delay_ms() DO NOT exist on the AVR target — they are PIC compiler intrinsics.',
    ],
    functions: [],
    macros: [
      { name: 'F_CPU', signature: '#define F_CPU 16000000UL', description: 'CPU frequency in Hz as an unsigned long; required by _delay_ms/_delay_us (the build passes -DF_CPU).' },
      { name: '_delay_ms(x)', signature: 'void _delay_ms(double ms)', description: 'Busy-waits for the given number of milliseconds (max 4294967.295 ms / F_CPU in MHz).' },
      { name: '_delay_us(x)', signature: 'void _delay_us(double us)', description: 'Busy-waits for the given number of microseconds (max 4294967.295 us / F_CPU in MHz).' },
    ],
  },
  {
    id: 'xc8.interrupt',
    name: 'Interrupts',
    include: '#include <xc.h>',
    description: 'Defining interrupt service routines: the avr-gcc style ISR() macro (always available on AVR targets) or the unified CCI __interrupt() keyword (requires -mext=cci).',
    notes: [
      'When targeting AVR devices XC8 uses the ISR() macro exactly like avr-gcc: ISR(TIMER0_OVF_vect) { /* ... */ } — the vector names follow the avr-libc <PERIPH>_<EVENT>_vect pattern, so existing avr-gcc handler names port across unchanged.',
      'The unified CCI syntax is void __interrupt(USART_RX_vect_num) my_isr(void) — the CCI (__interrupt, __at, __section…) must be enabled with the -mext=cci option (XC8 User Guide 4.1.1); without it, use ISR().',
      'Clearing the peripheral interrupt flag inside the ISR is user-code responsibility - forget it and the handler re-fires forever.',
      'Keep ISRs short: set a volatile flag and do the work in the main loop.',
    ],
    functions: [],
    macros: [
      { name: 'ISR(vector)', signature: 'ISR(TIMER0_OVF_vect) { /* handle, clear flag */ }', description: 'Defines an interrupt service routine bound to a device vector by name - the avr-gcc compatible form used for AVR targets.' },
      { name: '__interrupt(vect_num)', signature: 'void __interrupt(PORTF_PORT_vect_num) foo(void) { /* ... */ }', description: 'The Common C Interface keyword form (requires -mext=cci and <xc.h>) - marks the function as an interrupt routine bound to the vector number constant.' },
    ],
  },
  {
    id: 'xc8.config',
    name: 'Configuration bits',
    include: '#pragma config WDTON=SET  // in C source, no header needed',
    description: 'Setting device configuration bits (fuses) directly in C source with the #pragma config directive - the values land in the fuse sections of the linked image.',
    notes: [
      'AVR syntax: #pragma config setting = state, e.g. #pragma config WDTON = SET, EESAVE = CLEAR, BODLEVEL = BODLEVEL_4V3, LB = LB_NO_LOCK - one pragma can carry several comma-separated pairs.',
      'States other than SET/CLEAR are prefixed with the setting descriptor (BODLEVEL_4V3, SUT_CKSEL_14CK_62MS5…); a raw constant also works: #pragma config SUT_CKSEL = 0x10.',
      'The valid setting/value names per device are listed in the avr_chipinfo.html file of the compiler/DFP (xc8/avr/chipinfo) - review the device data sheet for their meaning.',
      'Setting-value pairs are NOT scanned by the preprocessor and must not be quoted; place the pragma outside function definitions.',
      'Bits not specified by a pragma get default values - Microchip recommends programming ALL the Configuration Word bits to prevent erratic behavior.',
      'The fuse sections do not ride the plain flash .hex the build produces - burn them with avrdude (-U lfuse/hfuse/…) or the Fuse Editor, exactly like with avr-gcc.',
    ],
    functions: [],
    macros: [
      { name: '#pragma config', signature: '#pragma config SETTING=STATE[,SETTING=VALUE…]', description: 'Sets configuration-word bits from C source; the valid names come from avr_chipinfo.html / the device datasheet.' },
      { name: 'FUSES struct', signature: 'FUSES = { .high = (FUSE_SPIEN) };', description: 'The legacy avr-libc-style fuse structure XC8-for-AVR also accepts (the CCI-documented replacement is #pragma config).' },
    ],
  },
  {
    id: 'xc8.stdio',
    name: '<stdio.h>',
    include: '#include <stdio.h>',
    description: 'XC8 C library formatted output and line input - the common subset available across all 8-bit targets.',
    notes: [
      'No floating-point formatting by default: %f/%e drag in a large software-float formatter, so keep printf() to integers and strings on small parts.',
      'All formatted output funnels through the single-character output routine - redirect stdio to a UART by overriding that hook (putch on classic PIC targets).',
      'gets() performs no bounds checking - an easy way to smash RAM on a microcontroller; prefer a fixed-size buffered reader.',
      'The printf machinery is code-size heavy; on tiny devices an itoa() plus puts() can save kilobytes.',
    ],
    functions: [
      { name: 'printf', signature: 'int printf(const char *format, ...)', description: 'Formats and writes text to the standard output stream.' },
      { name: 'sprintf', signature: 'int sprintf(char *buf, const char *format, ...)', description: 'Formats into a caller-supplied RAM buffer; returns the character count.' },
      { name: 'snprintf', signature: 'int snprintf(char *buf, size_t size, const char *format, ...)', description: 'Like sprintf but never writes more than size bytes including the terminator - the safe choice.' },
      { name: 'puts', signature: 'int puts(const char *s)', description: 'Writes a string plus a trailing newline to standard output.' },
      { name: 'putchar', signature: 'int putchar(int c)', description: 'Writes a single character; the printf/puts output path funnels through it, so overriding it redirects everything.' },
      { name: 'gets', signature: 'char *gets(char *s)', description: 'Reads one line from standard input into s with no bounds checking - unsafe on small RAMs.' },
    ],
    macros: [],
  },
  {
    id: 'xc8.string',
    name: '<string.h>',
    include: '#include <string.h>',
    description: 'XC8 C library memory and string utilities - the workhorses for buffer handling on 8-bit parts.',
    notes: [
      'Struct assignment and initialization compile down to block copies implemented by these same library routines, so memcpy/memset are tuned per core.',
      'Overlapping source and destination in memcpy is undefined - copy backwards or in blocks yourself.',
      'strncpy pads the remainder of the destination with zeros: copying a 1-character tail into a 64-byte buffer still writes all 64 bytes.',
      'String literals consume RAM on 8-bit targets - keep messages short or place them in program memory with the family-specific mechanism.',
    ],
    functions: [
      { name: 'memcpy', signature: 'void *memcpy(void *dest, const void *src, size_t n)', description: 'Copies n bytes between RAM buffers; the regions must not overlap.' },
      { name: 'memset', signature: 'void *memset(void *s, int c, size_t n)', description: 'Fills n bytes of s with the byte value c - the standard way to zero arrays and structs.' },
      { name: 'memcmp', signature: 'int memcmp(const void *s1, const void *s2, size_t n)', description: 'Compares n bytes and returns <0, 0 or >0 - handy for comparing fixed-size records.' },
      { name: 'strcmp', signature: 'int strcmp(const char *s1, const char *s2)', description: 'Compares two NUL-terminated strings; 0 means equal.' },
      { name: 'strcpy', signature: 'char *strcpy(char *dest, const char *src)', description: 'Copies a NUL-terminated string into dest with no bounds check - size the buffer yourself.' },
      { name: 'strncpy', signature: 'char *strncpy(char *dest, const char *src, size_t n)', description: 'Copies at most n bytes; pads with zeros when src is shorter and does not terminate when src is longer or exactly n.' },
      { name: 'strlen', signature: 'size_t strlen(const char *s)', description: 'Returns the string length excluding the NUL terminator.' },
      { name: 'strstr', signature: 'char *strstr(const char *s1, const char *s2)', description: 'Locates the first occurrence of s2 inside s1 (NULL if absent).' },
    ],
    macros: [],
  },
  {
    id: 'xc8.stdlib',
    name: '<stdlib.h>',
    include: '#include <stdlib.h>',
    description: 'XC8 C library numeric conversions, pseudo-random numbers and program termination.',
    notes: [
      'atoi()/atol() report no errors - a non-numeric string silently yields 0 or garbage; validate input yourself.',
      'rand() starts from the default seed 1, so every boot produces the same sequence unless srand() runs first.',
      'exit() never returns: on a microcontroller it ends in a reset or halt, not in an operating system.',
      'abs() operates on int only - roll your own for long or fixed-point values.',
    ],
    functions: [
      { name: 'abs', signature: 'int abs(int x)', description: 'Returns the absolute value of an int.' },
      { name: 'atoi', signature: 'int atoi(const char *s)', description: 'Parses a decimal integer from a string; no error detection.' },
      { name: 'atol', signature: 'long atol(const char *s)', description: 'Parses a decimal long from a string with the same no-error contract as atoi().' },
      { name: 'rand', signature: 'int rand(void)', description: 'Returns the next pseudo-random number in the range 0 to RAND_MAX.' },
      { name: 'srand', signature: 'void srand(unsigned int seed)', description: 'Seeds the pseudo-random generator (the default seed is 1).' },
      { name: 'exit', signature: 'void exit(int status)', description: 'Terminates the program - on a controller that is a reset or halt, never a return.' },
    ],
    macros: [],
  },
  {
    id: 'xc8.ctype',
    name: '<ctype.h>',
    include: '#include <ctype.h>',
    description: 'XC8 C library character classification and case conversion.',
    notes: [
      'Pass unsigned char values (or EOF): a signed char that went negative indexes outside the internal tables.',
      'The is* tests return non-zero on success, not necessarily 1 - test with if (isdigit(c)), never == 1.',
      'tolower()/toupper() leave non-letters unchanged, so no guard is needed around the call.',
    ],
    functions: [
      { name: 'isdigit', signature: 'int isdigit(int c)', description: 'Tests whether c is a decimal digit character (0-9).' },
      { name: 'isalpha', signature: 'int isalpha(int c)', description: 'Tests whether c is a letter.' },
      { name: 'isupper', signature: 'int isupper(int c)', description: 'Tests whether c is an uppercase letter.' },
      { name: 'tolower', signature: 'int tolower(int c)', description: 'Converts an uppercase letter to lowercase, leaving every other character unchanged.' },
      { name: 'toupper', signature: 'int toupper(int c)', description: 'Converts a lowercase letter to uppercase, leaving every other character unchanged.' },
    ],
    macros: [],
  },
  {
    id: 'xc8.math',
    name: '<math.h>',
    include: '#include <math.h>',
    description: 'XC8 C library floating-point mathematics - all of it executed in software on the 8-bit cores.',
    notes: [
      'Every call is software floating point: no FPU exists on PIC or AVR 8-bit parts, so sin()/pow() cost hundreds to thousands of cycles and pull in large library blocks.',
      'pow() is the heaviest of the family (exp/log machinery) - consider x*x, shifts or lookup tables first.',
      'Results are double, but printf() will not print them unless the float formatter is enabled - which costs even more flash.',
      'Fixed-point or integer math (e.g. (x*57)/100 instead of x*0.57) is the normal optimization on these devices.',
    ],
    functions: [
      { name: 'sin', signature: 'double sin(double x)', description: 'Software sine of x, with x in radians.' },
      { name: 'cos', signature: 'double cos(double x)', description: 'Software cosine of x, with x in radians.' },
      { name: 'tan', signature: 'double tan(double x)', description: 'Software tangent of x, with x in radians.' },
      { name: 'sqrt', signature: 'double sqrt(double x)', description: 'Software square root of x.' },
      { name: 'pow', signature: 'double pow(double x, double y)', description: 'Computes x raised to the power y - the heaviest routine of the family.' },
      { name: 'ceil', signature: 'double ceil(double x)', description: 'Smallest whole number not less than x.' },
      { name: 'floor', signature: 'double floor(double x)', description: 'Largest whole number not greater than x.' },
    ],
    macros: [],
  },
  {
    id: 'xc8.driver',
    name: 'xc8-cc (CLI driver)',
    include: 'xc8-cc -mcpu=ATmega328P -O2 -Wall -o firmware.hex main.c',
    description: 'The unified XC8 v2.x command-line driver: GCC-style options, one tool for every Microchip 8-bit device, compiling and linking in a single invocation.',
    notes: [
      'xc8-cc compiles AND links in one step: hand it the .c files plus options and it emits the full artifact set (.hex, .map, .sym, .lst, .p, .d and the .elf used by MPLAB).',
      'xc8-cc --version prints the compiler version - the first sanity check after installing.',
      'GCC-style options are used in v2: -o, -c, -I, -D, -O, -g, -std=, -Wall, -Werror and -v all behave familiarly.',
      'The old XC8 v1.x drivers picc/picc18 covered PIC only; v2.x replaces them with xc8-cc for all 8-bit families.',
      'Free (unlicensed) mode skips the PRO optimizations - --opt= PRO suboptions such as +asm stay unavailable; manage licenses with xclm.',
    ],
    functions: [],
    macros: [
      { name: '-mcpu=<device>', signature: 'xc8-cc -mcpu=ATmega328P main.c', description: 'Selects the target device - the one flag that switches the whole build between PIC and AVR parts (e.g. -mcpu=ATmega328P, -mcpu=16F18855).' },
      { name: '-o <file>', signature: 'xc8-cc -mcpu=16F18855 -o firmware.hex main.c', description: 'Names the output file; the other artifacts (.map/.sym/.lst/.p/.d/.elf) are generated alongside.' },
      { name: '-c', signature: 'xc8-cc -c -mcpu=16F18855 main.c', description: 'Compiles to object files without linking.' },
      { name: '-I<dir>', signature: 'xc8-cc -Isrc -Iinclude ...', description: 'Adds a directory to the include search path (no space after -I).' },
      { name: '-D<macro>[=val]', signature: 'xc8-cc -DDEBUG ...', description: 'Predefines a preprocessor macro, optionally with a value, from the command line.' },
      { name: '-O<level>', signature: '-O0 | -O1 | -O2 | -O3 | -Os', description: 'Optimization level; higher levels trade debuggability and compile time for smaller or faster code.' },
      { name: '-g', signature: 'xc8-cc -g -mcpu=ATmega328P main.c', description: 'Generates debug information for the ELF output (used by MPLAB and debuggers).' },
      { name: '-std=<std>', signature: '-std=c90 | -std=c99 | -std=c11', description: 'Selects the C dialect the sources are compiled against.' },
      { name: '-Wall', signature: 'xc8-cc -Wall ...', description: 'Enables the full warning set - the sensible default for new code.' },
      { name: '-Werror', signature: 'xc8-cc -Wall -Werror ...', description: 'Turns warnings into errors for CI-style builds.' },
      { name: '-v', signature: 'xc8-cc -v ...', description: 'Verbose mode: shows the tools and options as the driver runs them.' },
      { name: '--opt=<subopts>', signature: '--opt=+key,-key', description: 'Fine-grained XC8 optimization control with +add/-remove suboptions; PRO-only keys such as +asm require a paid license.' },
      { name: '--runtime=<subopts>', signature: '--runtime=+key,-key', description: 'Tunes the C runtime that gets linked in - which library routines and startup behaviour the build uses.' },
      { name: '--version', signature: 'xc8-cc --version', description: 'Prints the XC8 version banner and exits.' },
    ],
  },
  {
    id: 'xc8.devices',
    name: 'Supported devices',
    include: 'xc8-cc -mcpu=<device> ...  // PIC and AVR, one driver',
    description: 'The device families the XC8 v2.x driver covers: every Microchip 8-bit MCU - PIC10/12/16/18 plus the AVR ATmega, ATtiny and ATxmega lines.',
    notes: [
      '-mcpu takes the plain device name: -mcpu=ATmega328P for an AVR, -mcpu=16F18855 for a PIC (no "PIC" prefix).',
      'XC8 v2.x is the single compiler for ALL Microchip 8-bit devices - one install builds PIC and AVR firmware alike.',
      'XC8-AVR output is still a plain Intel HEX: avrdude flashes it exactly like an avr-gcc build.',
      'hexmate, the hex-merge utility bundled with XC8, can stitch images (e.g. bootloader + application) into one .hex.',
      'xclm is the XC8 license manager: free mode needs no license, PRO optimizations do.',
      'SFR names are not portable between families (TRISx/LATx on PIC vs DDRx/PORTx on AVR) - abstract device access when sharing sources.',
    ],
    functions: [],
    macros: [
      { name: 'PIC10', signature: 'e.g. -mcpu=10F200', description: 'Baseline-core PICs in the tiniest 6/8-pin packages.' },
      { name: 'PIC12', signature: 'e.g. -mcpu=12F1822', description: '8-pin baseline and mid-range PIC family.' },
      { name: 'PIC16', signature: 'e.g. -mcpu=16F18855', description: 'The classic mid-range PIC core - the biggest 8-bit PIC family.' },
      { name: 'PIC18', signature: 'e.g. -mcpu=18F45K22', description: 'Enhanced PIC core with more flash/RAM and richer peripherals - the most C-friendly PIC line.' },
      { name: 'ATmega', signature: 'e.g. -mcpu=ATmega328P', description: 'Classic AVR parts (the Arduino Uno MCU among them), built by the same xc8-cc driver.' },
      { name: 'ATtiny', signature: 'e.g. -mcpu=ATtiny85', description: 'Small AVR parts - also reachable from the unified driver.' },
      { name: 'ATxmega', signature: 'e.g. -mcpu=ATxmega128A1', description: 'XMEGA AVR parts with the event system and advanced peripherals.' },
    ],
  },
  {
    id: 'xc8.install',
    name: 'Installation',
    include: 'xc8-cc --version  // verify the driver is on PATH',
    description: 'Default MPLAB XC8 v2.x install locations per platform and how to verify the toolchain from a terminal.',
    notes: [
      'Windows default: C:\\Program Files\\Microchip\\xc8\\v2.xx\\bin (the driver is xc8-cc.exe).',
      'Linux default: /opt/microchip/xc8/v2.xx/bin.',
      'macOS default: /Applications/microchip/xc8/v2.xx/bin.',
      'Add the bin directory to PATH so xc8-cc resolves from any shell.',
      'Verify with xc8-cc --version; hexmate and xclm live in the same bin directory.',
      'XC8 v1.x installs expose the PIC-only picc/picc18 drivers instead - if those are what you find, upgrade to a v2.x install for xc8-cc and AVR support.',
    ],
    functions: [],
    macros: [],
  },
];
const MODULES_COUNT = MODULES.length;
const FUNCTIONS_COUNT = MODULES.reduce((n, m) => n + m.functions.length, 0);
module.exports = { MODULES, MODULES_COUNT, FUNCTIONS_COUNT };
